### ISSUE TITLE
Terms and conditions

### ISSUE THREAD

**Issue by merchanf** [FixIt-App/FixIt-Mobile#42]
In this page terms and conditions are defined.
ToDo:
- Research about how to do terms and conditions

**Comment by davidfcalle** [comment]
uando quiera que el Comercio tenga una integración API, el Comercio tendrá unos términos y condiciones para sus compradores en su sitio web, que incluyan el siguiente contenido (los “T&C de Compradores”):

a. Que el pagador utiliza el sistema de pago por su cuenta y riesgo.
b. Que el proveedor del sistema de pago no garantiza la disponibilidad o las demoras de la plataforma procesando las transacciones.
c. Que el proveedor del sistema de pago no garantiza la seguridad de la plataforma, y en particular la no ocurrencia de fraudes con la información del tarjetahabiente.
d. Que el proveedor del sistema de pago no garantiza el correcto ni oportuno procesamiento de las transacciones a través de la plataforma.
e. Que el proveedor del sistema de pago se exime de responsabilidad en relación con los bienes y/o servicios ofrecidos, su calidad, seguridad, idoneidad y tiempo de entrega.
f. Que el proveedor del sistema de pago no se hace responsable por el pago de los tributos que se causen como consecuencia de la relación contractual entre el Comercio y el Pagador.
g. Que el proveedor del sistema de pago se exime de responsabilidad por el incumplimiento del Comercio de sus obligaciones relacionadas con el manejo de datos personales.
h. Que el pagador autoriza al proveedor del sistema de pago para utilizar sus datos personales a fin de mitigar el riesgo de suplantación de identidad de los tarjetahabientes, enviarles información promocional y publicitaria PayU, de los comercios registrados en la Plataforma PayU y de terceros que incluyan promociones para la compra de bienes o servicios a través de la Plataforma PayU, enviar cupones de descuento, afiliar a programas de lealtad, crear perfiles de consumo del pagador, entre otros materiales promocionales y publicitarios que puedan llegar a ser de interés del pagador.
i. Que el pagador podrá solicitar al proveedor del sistema de pago, en cualquier momento, que no se le envíe información promocional o publicitaria, o que se le envíe sólo cierta información que sea de su interés.
